// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwUZs2woTReIMNB9aZV1fuRaBcCXSPxSQ',
    appId: '1:851556269464:web:685677795ec29827d5bfed',
    messagingSenderId: '851556269464',
    projectId: 'halal-social-prod',
    authDomain: 'halal-social-prod.firebaseapp.com',
    storageBucket: 'halal-social-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeUCE4rb-1mqu6F20Iagbe-cJJqj-doQs',
    appId: '1:851556269464:android:48c378808a8575ead5bfed',
    messagingSenderId: '851556269464',
    projectId: 'halal-social-prod',
    storageBucket: 'halal-social-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP4Zxz_ogQW6LWt9KKG8-2j4bScxiEfVg',
    appId: '1:851556269464:ios:289451ba556b8706d5bfed',
    messagingSenderId: '851556269464',
    projectId: 'halal-social-prod',
    storageBucket: 'halal-social-prod.firebasestorage.app',
    iosBundleId: 'com.example.mentorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP4Zxz_ogQW6LWt9KKG8-2j4bScxiEfVg',
    appId: '1:851556269464:ios:289451ba556b8706d5bfed',
    messagingSenderId: '851556269464',
    projectId: 'halal-social-prod',
    storageBucket: 'halal-social-prod.firebasestorage.app',
    iosBundleId: 'com.example.mentorApp',
  );
}
